package mybatis.dao;

import java.util.List;
import mybatis.model.EmployeeFlight;
import org.mybatis.cdi.Mapper;

@Mapper
public interface EmployeeFlightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_flight
     *
     * @mbg.generated Mon Apr 03 15:51:35 EEST 2023
     */
    int insert(EmployeeFlight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_flight
     *
     * @mbg.generated Mon Apr 03 15:51:35 EEST 2023
     */
    List<EmployeeFlight> selectAll();
}