package mybatis.dao;

import java.util.List;
import mybatis.model.Employee;
import org.mybatis.cdi.Mapper;

@Mapper
public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    int deleteByPrimaryKey(Integer employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    Employee selectByPrimaryKey(Integer employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    List<Employee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    int updateByPrimaryKey(Employee record);
}