package mybatis.dao;

import java.util.List;

import mybatis.model.Employee;
import mybatis.model.Flight;
import mybatis.model.Ticket;
import org.mybatis.cdi.Mapper;

@Mapper
public interface FlightMapper {
    List<Ticket> selectFlightTickets(Integer flightId);

    List<Employee> selectEmployeesForFlight(Integer flightId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.flight
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    int deleteByPrimaryKey(Integer flightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.flight
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    int insert(Flight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.flight
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    Flight selectByPrimaryKey(Integer flightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.flight
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    List<Flight> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.flight
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    int updateByPrimaryKey(Flight record);
}