package mybatis.dao;

import java.util.List;
import mybatis.model.Ticket;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    int deleteByPrimaryKey(Integer ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    int insert(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    Ticket selectByPrimaryKey(Integer ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    List<Ticket> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    int updateByPrimaryKey(Ticket record);
}