package mybatis.model;

public class EmployeeFlight {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee_flight.flight_id
     *
     * @mbg.generated Mon Apr 03 15:51:35 EEST 2023
     */
    private Integer flightId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee_flight.employee_id
     *
     * @mbg.generated Mon Apr 03 15:51:35 EEST 2023
     */
    private Integer employeeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee_flight.flight_id
     *
     * @return the value of public.employee_flight.flight_id
     *
     * @mbg.generated Mon Apr 03 15:51:35 EEST 2023
     */
    public Integer getFlightId() {
        return flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee_flight.flight_id
     *
     * @param flightId the value for public.employee_flight.flight_id
     *
     * @mbg.generated Mon Apr 03 15:51:35 EEST 2023
     */
    public void setFlightId(Integer flightId) {
        this.flightId = flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee_flight.employee_id
     *
     * @return the value of public.employee_flight.employee_id
     *
     * @mbg.generated Mon Apr 03 15:51:35 EEST 2023
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee_flight.employee_id
     *
     * @param employeeId the value for public.employee_flight.employee_id
     *
     * @mbg.generated Mon Apr 03 15:51:35 EEST 2023
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
}