package mybatis.model;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.employee_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.cell_phone
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private String cellPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.name
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.role
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.surname
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.employee_id
     *
     * @return the value of public.employee.employee_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.employee_id
     *
     * @param employeeId the value for public.employee.employee_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.cell_phone
     *
     * @return the value of public.employee.cell_phone
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public String getCellPhone() {
        return cellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.cell_phone
     *
     * @param cellPhone the value for public.employee.cell_phone
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.name
     *
     * @return the value of public.employee.name
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.name
     *
     * @param name the value for public.employee.name
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.role
     *
     * @return the value of public.employee.role
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.role
     *
     * @param role the value for public.employee.role
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.surname
     *
     * @return the value of public.employee.surname
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.surname
     *
     * @param surname the value for public.employee.surname
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }
}