package mybatis.model;

import java.util.List;

public class Flight {
    private List<Ticket> tickets;

    public List<Ticket> getTickets(){
        return tickets;
    }

    public void setTickets(List<Ticket> tickets){
        this.tickets = tickets;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.flight.flight_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private Integer flightId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.flight.arrival_airport
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private String arrivalAirport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.flight.arrival_time
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private Integer arrivalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.flight.departure_airport
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private String departureAirport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.flight.departure_time
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private Integer departureTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.flight.name
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.flight.plane_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private Integer planeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.flight.flight_id
     *
     * @return the value of public.flight.flight_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public Integer getFlightId() {
        return flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.flight.flight_id
     *
     * @param flightId the value for public.flight.flight_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setFlightId(Integer flightId) {
        this.flightId = flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.flight.arrival_airport
     *
     * @return the value of public.flight.arrival_airport
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public String getArrivalAirport() {
        return arrivalAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.flight.arrival_airport
     *
     * @param arrivalAirport the value for public.flight.arrival_airport
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setArrivalAirport(String arrivalAirport) {
        this.arrivalAirport = arrivalAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.flight.arrival_time
     *
     * @return the value of public.flight.arrival_time
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public Integer getArrivalTime() {
        return arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.flight.arrival_time
     *
     * @param arrivalTime the value for public.flight.arrival_time
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setArrivalTime(Integer arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.flight.departure_airport
     *
     * @return the value of public.flight.departure_airport
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public String getDepartureAirport() {
        return departureAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.flight.departure_airport
     *
     * @param departureAirport the value for public.flight.departure_airport
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setDepartureAirport(String departureAirport) {
        this.departureAirport = departureAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.flight.departure_time
     *
     * @return the value of public.flight.departure_time
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public Integer getDepartureTime() {
        return departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.flight.departure_time
     *
     * @param departureTime the value for public.flight.departure_time
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setDepartureTime(Integer departureTime) {
        this.departureTime = departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.flight.name
     *
     * @return the value of public.flight.name
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.flight.name
     *
     * @param name the value for public.flight.name
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.flight.plane_id
     *
     * @return the value of public.flight.plane_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public Integer getPlaneId() {
        return planeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.flight.plane_id
     *
     * @param planeId the value for public.flight.plane_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setPlaneId(Integer planeId) {
        this.planeId = planeId;
    }
}