package mybatis.model;

public class Plane {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.plane.plane_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private Integer planeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.plane.model
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.plane.flight_hours
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private Integer flightHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.plane.registration
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private String registration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.plane.plane_id
     *
     * @return the value of public.plane.plane_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public Integer getPlaneId() {
        return planeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.plane.plane_id
     *
     * @param planeId the value for public.plane.plane_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setPlaneId(Integer planeId) {
        this.planeId = planeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.plane.model
     *
     * @return the value of public.plane.model
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.plane.model
     *
     * @param model the value for public.plane.model
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.plane.flight_hours
     *
     * @return the value of public.plane.flight_hours
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public Integer getFlightHours() {
        return flightHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.plane.flight_hours
     *
     * @param flightHours the value for public.plane.flight_hours
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setFlightHours(Integer flightHours) {
        this.flightHours = flightHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.plane.registration
     *
     * @return the value of public.plane.registration
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public String getRegistration() {
        return registration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.plane.registration
     *
     * @param registration the value for public.plane.registration
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setRegistration(String registration) {
        this.registration = registration;
    }
}