package mybatis.model;

public class Ticket {
    private Flight ticketFlight;

    public Flight getTicketFlight(){
        return ticketFlight;
    }

    public void setTicketFlight(Flight ticketFlight){
        this.ticketFlight = ticketFlight;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.ticket_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private Integer ticketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.is_bought
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private Boolean isBought;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.price
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.seat
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private Integer seat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.ticket_class
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private String ticketClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.flight_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    private Integer flightId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.ticket_id
     *
     * @return the value of public.ticket.ticket_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public Integer getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.ticket_id
     *
     * @param ticketId the value for public.ticket.ticket_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.is_bought
     *
     * @return the value of public.ticket.is_bought
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public Boolean getIsBought() {
        return isBought;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.is_bought
     *
     * @param isBought the value for public.ticket.is_bought
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setIsBought(Boolean isBought) {
        this.isBought = isBought;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.price
     *
     * @return the value of public.ticket.price
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.price
     *
     * @param price the value for public.ticket.price
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.seat
     *
     * @return the value of public.ticket.seat
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public Integer getSeat() {
        return seat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.seat
     *
     * @param seat the value for public.ticket.seat
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setSeat(Integer seat) {
        this.seat = seat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.ticket_class
     *
     * @return the value of public.ticket.ticket_class
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public String getTicketClass() {
        return ticketClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.ticket_class
     *
     * @param ticketClass the value for public.ticket.ticket_class
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setTicketClass(String ticketClass) {
        this.ticketClass = ticketClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.flight_id
     *
     * @return the value of public.ticket.flight_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public Integer getFlightId() {
        return flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.flight_id
     *
     * @param flightId the value for public.ticket.flight_id
     *
     * @mbg.generated Mon Apr 03 14:52:15 EEST 2023
     */
    public void setFlightId(Integer flightId) {
        this.flightId = flightId;
    }
}